### ISSUE TITLE
Missing stuff in hooks.

### ISSUE THREAD

**Issue by Snukii** [starbasehq/sveltekit-openid-connect#5]
I'm trying to use this package but there appears to be a bunch of stuff missing in the hooks file?

All the variables for the config are missing.

in handle(), `headers`, `sessionName`, `logger` and `context` are missing.

As indicated by the comment _This is a service that provides session storage, not a part of this package_ the session storage is also missing, shouldn't that be a part of the package?

in getSession() `request` is missing.

How is this supposed to work with all these things missing?

**Comment by ChrisOgden** [comment]
@Snukii the session service that I mention is custom to my implementation, it wouldn't make sense for me to include that code unless it was stubbed out and empty. I am not sure how others would want to store their sessions, they could do it via files, database, redis or any other. Are you looking for just a stub example of that class structure?

Other items

- getSession() request - I updated the readme, this was a breaking change in sveltekit and I forgot to update the docs
- handle() headers - This is defined everywhere I see it in the README, am I missing something?
- handle() sessionName - updated README
- handle() logger - This is my own logging function, switched to console.warn in README
- handle() context - I updated the readme, this was a breaking change in sveltekit and I forgot to update the docs

**Comment by Snukii** [comment]
I think including the simplest working solution for the session storage would be nice, that way it at least works out of the box and people can customize as needed.


Most of the fixes you did seems to work 👍🏻 

handle() headers is still an issue on my end:

![image](https://user-images.githubusercontent.com/6986109/142820303-325e5720-3931-4843-a68d-a2969aa4f6fe.png)

There simply is no defined `headers`.


Making all the `AUTH0_` variables and `API_HOST` environment variables would probably also be a good idea.

**Comment by ChrisOgden** [comment]
I should have an update to this today. There are some changes required due to sveltekit changes so it is a natural time to do this.
